"""Default configuration values."""

import os

# Theme defaults
DEFAULT_THEME = "null-dark"

# Shell defaults
DEFAULT_SHELL = os.environ.get("SHELL", "/bin/bash")

# AI provider defaults - no default provider, user must configure
DEFAULT_AI_PROVIDER = ""
DEFAULT_AI_MODEL = ""
DEFAULT_AI_ENDPOINT = ""
DEFAULT_AI_ACTIVE_PROMPT = "default"
DEFAULT_AGENT_MODE = False

# Context defaults
DEFAULT_CONTEXT_WINDOW = 4000
DEFAULT_MAX_TOKENS = 2048
DEFAULT_TEMPERATURE = 0.7

# Agent approval defaults
DEFAULT_AGENT_APPROVAL_TIMEOUT = 60  # seconds

# Connection pool defaults
DEFAULT_POOL_MAX_CONNECTIONS = 100
DEFAULT_POOL_MAX_KEEPALIVE = 20
DEFAULT_POOL_KEEPALIVE_EXPIRY = 30.0
DEFAULT_POOL_CONNECT_TIMEOUT = 10.0
DEFAULT_POOL_READ_TIMEOUT = 120.0

# Model cache defaults
DEFAULT_MODEL_CACHE_TTL = 300.0  # 5 minutes in seconds

# Timing defaults (seconds)
DEFAULT_EXECUTOR_POLL_INTERVAL = 0.01
DEFAULT_EXECUTOR_YIELD_INTERVAL = 0.0
DEFAULT_EXECUTOR_CANCEL_GRACE_PERIOD = 0.1
DEFAULT_SIDEBAR_UPDATE_INTERVAL = 2.0
DEFAULT_PROVIDER_MODEL_LOAD_DELAY = 0.5
DEFAULT_AGENT_LOOP_INTERVAL = 0.1
DEFAULT_RAG_BATCH_YIELD = 0.001
DEFAULT_RAG_PROGRESS_INTERVAL = 0.01
DEFAULT_RATE_LIMITER_BACKOFF = 1.0
DEFAULT_SSH_RECONNECT_DELAY = 1.0
DEFAULT_MCP_HEALTH_CHECK_INTERVAL = 60.0
